// packages/core/src/utils/defaultPlaceholders.ts

export const defaultPlaceholders = {
  NOMBRE_ASISTENTE_VIRTUAL: "",
  CONFIGURACION_SALUDO_INICIAL_ASISTENTE_VIRTUAL: "",
  NOMBRE_CLINICA: "",
  DIRECCION_CLINICA: "",
  APARCAMIENTO_CLINICA: "",
  TELEFONO_CLINICA: "",
  HORARIOS_DE_ATENCION_CLINICA: "",
  REDES_SOCIALES_CLINICA: "",
  PAGINA_WEB_CLINICA: "",
  CORREO_ELECTRONICO_CLINICA: "",
  PREGUNTAS_FRECUENTES: "",
  CATALOGO_TRATAMIENTOS: "",
  MOTIVOS_TAREA: "",
  LISTA_DE_SEDES_DE_LA_CLINICA: "",
  LOS_ESPACIOS_SON_O_NO_SON_SEDES: "",
  MENSAJE_ESTRUCTURADO_CITA_CONFIRMADA: "",
  MENSAJE_ESTRUCTURADO_CITA_REPROGRAMADA: "",
  MENSAJE_ESTRUCTURADO_PARA_CONFIRMAR_CANCELACION: "",
  RESTRICCIONES_EN_DISPONIBILIDADES: "",
  CONFIGURACION_FLUJOS_CITAS: "",
};