// packages/core/src/utils/defaultPlaceholders.ts

export const defaultPlaceholders = {
  DATOS_CLINICA: `
  NOMBRE_CLINICA: "",
  TELEFONO_CLINICA: "",
  DIRECCION_CLINICA: "",
  PAGINA_WEB_CLINICA: "",
  APARCAMIENTO_CLINICA: "",
  REDES_SOCIALES_CLINICA: "",
  CORREO_ELECTRONICO_CLINICA: "",
  HORARIOS_DE_ATENCION_CLINICA: "",
  LISTA_DE_SEDES_DE_LA_CLINICA: "[USAR LOS MISMOS NOMBRES QUE EN EL SOFTWARE]",
  `,
  LOS_ESPACIOS_SON_O_NO_SON_SEDES: `Los espacios SÍ son sedes / Los espacios NO son sedes`,
  CONFIGURACION_INTERACCION_ASISTENTE: "",
  CONFIGURACION_DE_DISPONIBILIDADES: "",
  CATALOGO_TRATAMIENTOS: "",
  PREGUNTAS_FRECUENTES: "",
  MOTIVOS_TAREA: "",
};